// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_tPZLgJO2I3zmS-2GT_oJlQf57EOE8vQ',
    appId: '1:126977464854:web:20146e2a8045c3eb5f3337',
    messagingSenderId: '126977464854',
    projectId: 'task-man-app-3',
    authDomain: 'task-man-app-3.firebaseapp.com',
    storageBucket: 'task-man-app-3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg5eQwAtdaO8xwWN5Df1FL1qx8vH6_tS4',
    appId: '1:126977464854:android:1921d6d00d9acc195f3337',
    messagingSenderId: '126977464854',
    projectId: 'task-man-app-3',
    storageBucket: 'task-man-app-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzLJAL8kxvhvBY66-Dk56k4f0P1IhviAs',
    appId: '1:126977464854:ios:74e7eb36430c4f265f3337',
    messagingSenderId: '126977464854',
    projectId: 'task-man-app-3',
    storageBucket: 'task-man-app-3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzLJAL8kxvhvBY66-Dk56k4f0P1IhviAs',
    appId: '1:126977464854:ios:74e7eb36430c4f265f3337',
    messagingSenderId: '126977464854',
    projectId: 'task-man-app-3',
    storageBucket: 'task-man-app-3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_tPZLgJO2I3zmS-2GT_oJlQf57EOE8vQ',
    appId: '1:126977464854:web:81fc9068c4de47e65f3337',
    messagingSenderId: '126977464854',
    projectId: 'task-man-app-3',
    authDomain: 'task-man-app-3.firebaseapp.com',
    storageBucket: 'task-man-app-3.firebasestorage.app',
  );
}
